# Generated by Django 5.1.5 on 2025-10-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='Опис про себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто проживання')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ім’я')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Надіслано')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='Заклад освіти')),
                ('degree', models.CharField(max_length=100, verbose_name='Спеціальність / ступінь')),
                ('start_year', models.IntegerField(verbose_name='Рік початку навчання')),
                ('end_year', models.IntegerField(verbose_name='Рік закінчення навчання')),
            ],
        ),
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва цілі')),
                ('description', models.TextField(verbose_name='Опис плану')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Кінцевий термін')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ім’я')),
                ('profession', models.CharField(max_length=100, verbose_name='Професія / роль')),
                ('introduction', models.TextField(verbose_name='Коротке привітання')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва навички')),
                ('level', models.IntegerField(default=0, verbose_name='Рівень володіння (%)')),
            ],
        ),
    ]
